export const contact = {
  title: 'Contact us',
  description:
    'On this website, we will only use your personal data to respond to your message. By clicking on "send", you explicitly agree that your email address will be used exclusively to contact you in order to respond to your request or question. We will not use any cookies generated by the site that you are not aware of. ',
  note: 'Fields marked with an asterisk (*) are required.',
  form: {
    firstname: 'Your name *',
    lastname: 'Your first name *',
    email: 'Your email address *',
    telephone: 'Your phone number',
    message: 'Your message...',
    submit: 'Send',
  },
}
